
SCR = 2
REGA = SCR +2
REGX = REGA +1
REGY = REGX +1

TV = REGY +1
TH = TV +1

AND_LO_LO = TH +1
AND_LO_HI = AND_LO_LO +1
AND_HI_LO = AND_LO_HI +1
AND_HI_HI = AND_HI_LO +1
ORA_LO_LO = AND_HI_HI +1
ORA_LO_HI = ORA_LO_LO +1
ORA_HI_LO = ORA_LO_HI +1
ORA_HI_HI = ORA_HI_LO +1

SPR_CNT = SCR

*= 2049
!byte $0c,$08,$0a,$00,$9e   ; Line 10 SYS
!tx "2070"            ; Address for sys start in text 4096+11
*= 2070

 SEI        ; disable maskable IRQs

 LDA #$7F
 STA $DC0D  ; disable timer interrupts which can be generated by the two CIA chips
 STA $DD0D  ; the kernal uses such an interrupt to flash the cursor and scan the keyboard, so we better stop it.

 LDA $DC0D  ; by reading this two registers we negate any pending CIA irqs.
 LDA $DD0D  ; if we don't do this, a pending CIA irq might occur after we finish setting up our irq. we don't want that to happen.

 LDA #$01   ; this is how to tell the VICII to generate a raster interrupt
 STA $D01A
 LDA #$FB   ; this is how to tell at which rasterline we want the irq to be triggered
 STA $D012

 LDA #%00110000 ; 00111011 ; 76543210 - 7=MSBRST 6=ECM 5=BM 4=VIS 3=25/24 0-2=SCRL
 STA $D011    ;VIC Control Register 1

 LDA #%00011000 ; 0-2=SCRL 3=40/38 4=MCM 5-7=UNUSED
 STA $D016    ;VIC Control Register 2

 LDA #$35   ; we turn off the BASIC and KERNAL rom here
 STA $01    ; the cpu now sees RAM everywhere except at $d000-$e000, where still the registers of SID/VICII/etc are visible

 ldA #<BM_IRQ  ; this is how we set up
 STA $FFFE     ; the address of our interrupt code
 LDA #>BM_IRQ
 STA $FFFF
  
 LDA #<NMI_NOP ; lsb
 STA $FFFA ; Create a nop, irq handler for NMI that gets called whenever RESTORE is pressed or similar.
 LDA #>NMI_NOP ; msb
 STA $FFFB ; We're putting our irq handler directly in the vector that usually points to the kernal's NMI handler since we have kernal banked out.

 LDA #$00  ; Force an NMI by setting up a timer. This will cause an NMI, that won't be acked. Any subsequent NMI's from RESTORE will be essentially disabled.
 STA $DD0E       ; Stop timer A
 STA $DD04       ; Set timer A to 0, NMI will occure immediately after start
 STA $DD0E

 LDA #$81
 STA $DD0D       ; Set timer A as source for NMI

 LDA #$01
 STA $DD0E       ; Start timer A -> NMI

 LDA #$02 ; 01 ; 02
 STA $DD00 ; bank
    
 LDA #%01111000 ; $80     ; 10000000 = screen at 16k - colour at 24k / 01111000 = screen at 24k / colour at 23k
 STA $D018    ;VIC Memory Control Register - screen at bank 0 - colour at bank 8 

 LDA #$00
 STA $D021

 LDA #$01 ; colour 01 (0000????) and colour 10 (????0000) - bank 1
 LDX #<SCN
 LDY #>SCN 
 STX SCR+0
 STY SCR+1
 LDX #>8000 
 LDY #<8000
 JSR MEMSET

 LDA #$01 ; $01 ; colour 11 
 LDX #<$D800
 LDY #>$D800
 STX SCR+0
 STY SCR+1
 LDX #>1000 
 LDY #<1000
 JSR MEMSET

 LDA #$BC ; colour 01 (0000????) and colour 10 (????0000) - bank 1
 LDX #<COL_BUF
 LDY #>COL_BUF 
 STX SCR+0
 STY SCR+1
 LDX #>1000 
 LDY #<1000
 JSR MEMSET
 
 JSR SB_FILL
 
;CLI ; enable maskable interrupts again

 LDA #32
 STA TH
 STA TV

MLOOP:
 JSR V_WAIT

 LDY TH
 LAX TV
 JSR BAK_SCN ; background to screen
 
 JSR JOYSTICK

 LDX TH
 LDa TV
 LDy #0
 JSR SPR_SCN ; sprite to screen


JMP MLOOP ; we better don't RTS, the ROMS are now switched off, there's no way back to the system

FIRE !BYTE 0

!ZONE JOYSTICK
JOYSTICK: LDA $DC00
          LSR
          BCS   .UP
            DEC   TV
.UP       LSR
          BCS   .DOWN
            INC   TV
.DOWN     LSR
          BCS   .LEFT
            DEC   TH
.LEFT     LSR
          BCS   .RIGHT
            INC   TH
.RIGHT    AND   #1
          STA   FIRE
          RTS

!ZONE V_WAIT
V_WAIT  LDA   #248
.LOOP     CMP   $D012
          BNE   .LOOP
        INC   $D020
        DEC   $D020
        RTS

BM_IRQ:   INC   $D019    ;VIC Interrupt Request Register (IRR)
          PHA
          TXA 
          PHA
          TYA 
          PHA 

          PLA 
          TAY
          PLA 
          TAX
          PLA
NMI_NOP:  RTI ; This is the irq handler for the NMI. Just returns without acknowledge. This prevents subsequent NMI's from interfering.

!ZONE SB_FILL
SB_FILL:  LDX   #31
.LOOP_H   LDY   #24
.LOOP_V       JSR   CHAR_SB_2
              DEY
              BPL   .LOOP_V
            DEX
            BPL   .LOOP_H
          RTS 
  
CHAR_SB_2 STY   REGY
          TYA
          ASL ; *2
          ASL ; *4
          ASL ; *8
          TAY
          LDA   SC_LO,Y
          STA   SCR 
          LDA   SC_HI,Y
         ora #128 
          STA   SCR+1 
          STX   REGX
          TXA
          ASL ; *2
          ASL ; *4
          ASL ; *8
          TAY
          LDA   REGY
          CLC
          ADC   REGX
          AND   #15
          TAX
          LDA   PATTERN,X
          LDX   #8
.LOOP:      STA   (SCR),Y
            INY
            DEX
            BNE   .LOOP
          LDX   REGX
          LDY   REGY
          RTS 

!ZONE MEMSET        
MEMSET       STY    .LSB_ONLY+1 ; store LSB count
             CPX    #0          ; MSB?     
             BEQ    .LSB_ONLY   ; no

             LDY    #0          ; yes so reset LSB
.MSB_LOOP  
.LSB_LOOP      STA    (SCR),Y   ; clear whole MSB
               DEY 
               BNE    .LSB_LOOP

              INC    SCR+1      ; inc MSB
              DEX               ; dec MSB count
              BNE    .MSB_LOOP

.LSB_ONLY    LDY    #0          ; LSB count 
             BEQ    .MS_END     ; not needed

.LAST_LSB_LOOP STA   (SCR),Y
               DEY 
               BNE   .LAST_LSB_LOOP
                
              STA   (SCR),Y     ; clear last Y (0)
 
.MS_END      RTS

!ZONE SPR_SCN ; copy sprite to screen
SPR_SCN

 DEC $D020

  STA REGY ; V

  LDA   SPRITE_AND_LO_LO,Y
  STA   .AND_LO+1
  LDA   SPRITE_AND_LO_HI,Y
  STA   .AND_LO+2
  LDA   SPRITE_AND_HI_LO,Y
  STA   .AND_HI+1
  LDA   SPRITE_AND_HI_HI,Y
  STA   .AND_HI+2
  
  LDA   SPRITE_ORA_LO_LO,Y
  STA   .ORA_LO+1
  LDA   SPRITE_ORA_LO_HI,Y
  STA   .ORA_LO+2

  STX REGX ; H
  lda #3 
  AXS #0
;  TXA
;  AND     #3
;  TAX

.AND_LO   LDy $ABCD,X
          STy .SPA01 +1
          INy 
          STy .SPA02 +1
          INy 
          STy .SPA03 +1
          INy 
          STy .SPA04 +1
          INy 
          STy .SPA05 +1
          INy 
          STy .SPA06 +1
          INy 
          STy .SPA07 +1
          INy 
          STy .SPA08 +1
          INy 
          STy .SPA09 +1
          INy 
          STy .SPA10 +1
          INy 
          STy .SPA11 +1
          INy 
          STy .SPA12 +1
          INy 
          STy .SPA13 +1
          INy 
          STy .SPA14 +1
          INy 
          STy .SPA15 +1
          INy 
          STy .SPA16 +1
          INY 
          STY .SPA17 +1
          INY 
          STY .SPA18 +1
          INY 
          STY .SPA19 +1
          INY 
          STY .SPA20 +1
          INY 
          STY .SPA21 +1
;          INY 
;          STY .SPA22 +1
;          INY 
;          STY .SPA23 +1
;          INY 
;          STY .SPA24 +1
.AND_HI   LDa $ABCD,X
          STa .SPA01 +2
          STa .SPA02 +2
          STa .SPA03 +2
          STa .SPA04 +2
          STa .SPA05 +2
          STa .SPA06 +2
          STa .SPA07 +2
          STa .SPA08 +2
          STa .SPA09 +2
          STa .SPA10 +2
          STa .SPA11 +2
          STa .SPA12 +2
          STa .SPA13 +2
          STa .SPA14 +2
          STa .SPA15 +2
          STa .SPA16 +2
          STA .SPA17 +2
          STA .SPA18 +2
          STA .SPA19 +2
          STA .SPA20 +2
          STA .SPA21 +2
;          STA .SPA22 +2
;          STA .SPA23 +2
;          STA .SPA24 +2

          STa .SPO01 +2
          STa .SPO02 +2
          STa .SPO03 +2
          STa .SPO04 +2
          STa .SPO05 +2
          STa .SPO06 +2
          STa .SPO07 +2
          STa .SPO08 +2
          STa .SPO09 +2
          STa .SPO10 +2
          STa .SPO11 +2
          STa .SPO12 +2
          STa .SPO13 +2
          STa .SPO14 +2
          STa .SPO15 +2
          STa .SPO16 +2
          STA .SPO17 +2
          STA .SPO18 +2
          STA .SPO19 +2
          STA .SPO20 +2
          STA .SPO21 +2
;          STA .SPO22 +2
;          STA .SPO23 +2
;          STA .SPO24 +2

.ORA_LO   LDy $ABCD,X
          STy .SPO01 +1
          INy 
          STy .SPO02 +1
          INy 
          STy .SPO03 +1
          INy 
          STy .SPO04 +1
          INy 
          STy .SPO05 +1
          INy 
          STy .SPO06 +1
          INy 
          STy .SPO07 +1
          INy 
          STy .SPO08 +1
          INy 
          STy .SPO09 +1
          INy
          STy .SPO10 +1
          INy 
          STy .SPO11 +1
          INy 
          STy .SPO12 +1
          INy 
          STy .SPO13 +1
          INy 
          STy .SPO14 +1
          INy 
          STy .SPO15 +1
          INy 
          STy .SPO16 +1
          INY 
          STY .SPO17 +1
          INY 
          STY .SPO18 +1
          INY 
          STY .SPO19 +1
          INY 
          STY .SPO20 +1
          INY 
          STY .SPO21 +1
;          INY 
;          STY .SPO22 +1
;          INY 
;          STY .SPO23 +1
;          INY 
;          STY .SPO24 +1

 DEC $D020

 LAX REGY ; V
 AND #7
 ASL
 STA .JMP +1
.JMP JMP (SPR_SCN_TAB)

.SPR_SCN_00
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1
 INY
 STY  .SRC02+1
 STY  .DST02+1
 INY
 STY  .SRC03+1
 STY  .DST03+1
 INY
 STY  .SRC04+1
 STY  .DST04+1
 INY
 STY  .SRC05+1
 STY  .DST05+1
 INY
 STY  .SRC06+1
 STY  .DST06+1
 INY
 STY  .SRC07+1
 STY  .DST07+1
 INY
 STY  .SRC08+1
 STY  .DST08+1

 LDY  SC_LO+8,X
 STY  .SRC09+1
 STY  .DST09+1
 INY
 STY  .SRC10+1
 STY  .DST10+1
 INY
 STY  .SRC11+1
 STY  .DST11+1
 INY
 STY  .SRC12+1
 STY  .DST12+1
 INY
 STY  .SRC13+1
 STY  .DST13+1
 INY
 STY  .SRC14+1
 STY  .DST14+1
 INY
 STY  .SRC15+1
 STY  .DST15+1
 INY
 STY  .SRC16+1
 STY  .DST16+1

 LDY  SC_LO+16,X
 STY  .SRC17+1
 STY  .DST17+1
 INY
 STY  .SRC18+1
 STY  .DST18+1
 INY
 STY  .SRC19+1
 STY  .DST19+1
 INY
 STY  .SRC20+1
 STY  .DST20+1
 INY
 STY  .SRC21+1
 STY  .DST21+1
; INY
; STY  .SRC22+1
; STY  .DST22+1
; INY
; STY  .SRC23+1
; STY  .DST23+1
; INY
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .SRC01+2
 STA  .DST01+2
 STA  .SRC02+2
 STA  .DST02+2
 STA  .SRC03+2
 STA  .DST03+2
 STA  .SRC04+2
 STA  .DST04+2
 STA  .SRC05+2
 STA  .DST05+2
 STA  .SRC06+2
 STA  .DST06+2
 STA  .SRC07+2
 STA  .DST07+2
 STA  .SRC08+2
 STA  .DST08+2

 LDA  SC_HI+8,X
 STA  .SRC09+2
 STA  .DST09+2
 STA  .SRC10+2
 STA  .DST10+2
 STA  .SRC11+2
 STA  .DST11+2
 STA  .SRC12+2
 STA  .DST12+2
 STA  .SRC13+2
 STA  .DST13+2
 STA  .SRC14+2
 STA  .DST14+2
 STA  .SRC15+2
 STA  .DST15+2
 STA  .SRC16+2
 STA  .DST16+2

 LDA  SC_HI+16,X
 STA  .SRC17+2
 STA  .DST17+2
 STA  .SRC18+2
 STA  .DST18+2
 STA  .SRC19+2
 STA  .DST19+2
 STA  .SRC20+2
 STA  .DST20+2
 STA  .SRC21+2
 STA  .DST21+2
; STA  .SRC22+2
; STA  .DST22+2
; STA  .SRC23+2
; STA  .DST23+2
; STA  .SRC24+2
; STA  .DST24+2
 JMP .SETUP

.SPR_SCN_01
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1
 INY
 STY  .SRC02+1
 STY  .DST02+1
 INY
 STY  .SRC03+1
 STY  .DST03+1
 INY
 STY  .SRC04+1
 STY  .DST04+1
 INY
 STY  .SRC05+1
 STY  .DST05+1
 INY
 STY  .SRC06+1
 STY  .DST06+1
 INY
 STY  .SRC07+1
 STY  .DST07+1

 LDY  SC_LO+7,X
 STY  .SRC08+1
 STY  .DST08+1
 INY
 STY  .SRC09+1
 STY  .DST09+1
 INY
 STY  .SRC10+1
 STY  .DST10+1
 INY
 STY  .SRC11+1
 STY  .DST11+1
 INY
 STY  .SRC12+1
 STY  .DST12+1
 INY
 STY  .SRC13+1
 STY  .DST13+1
 INY
 STY  .SRC14+1
 STY  .DST14+1
 INY
 STY  .SRC15+1
 STY  .DST15+1

 LDY  SC_LO+15,X
 STY  .SRC16+1
 STY  .DST16+1
 INY
 STY  .SRC17+1
 STY  .DST17+1
 INY
 STY  .SRC18+1
 STY  .DST18+1
 INY
 STY  .SRC19+1
 STY  .DST19+1
 INY
 STY  .SRC20+1
 STY  .DST20+1
 INY
 STY  .SRC21+1
 STY  .DST21+1
; INY
; STY  .SRC22+1
; STY  .DST22+1
; INY
; STY  .SRC23+1
; STY  .DST23+1

; LDY  SC_LO+23,X
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .SRC01+2
 STA  .DST01+2
 STA  .SRC02+2
 STA  .DST02+2
 STA  .SRC03+2
 STA  .DST03+2
 STA  .SRC04+2
 STA  .DST04+2
 STA  .SRC05+2
 STA  .DST05+2
 STA  .SRC06+2
 STA  .DST06+2
 STA  .SRC07+2
 STA  .DST07+2

 LDA  SC_HI+7,X
 STA  .SRC08+2
 STA  .DST08+2
 STA  .SRC09+2
 STA  .DST09+2
 STA  .SRC10+2
 STA  .DST10+2
 STA  .SRC11+2
 STA  .DST11+2
 STA  .SRC12+2
 STA  .DST12+2
 STA  .SRC13+2
 STA  .DST13+2
 STA  .SRC14+2
 STA  .DST14+2
 STA  .SRC15+2
 STA  .DST15+2

 LDA  SC_HI+15,X
 STA  .SRC16+2
 STA  .DST16+2
 STA  .SRC17+2
 STA  .DST17+2
 STA  .SRC18+2
 STA  .DST18+2
 STA  .SRC19+2
 STA  .DST19+2
 STA  .SRC20+2
 STA  .DST20+2
 STA  .SRC21+2
 STA  .DST21+2
; STA  .SRC22+2
; STA  .DST22+2
; STA  .SRC23+2
; STA  .DST23+2

; LDA  SC_HI+23,X
; STA  .SRC24+2
; STA  .DST24+2
 JMP .SETUP

.SPR_SCN_02
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1
 INY
 STY  .SRC02+1
 STY  .DST02+1
 INY
 STY  .SRC03+1
 STY  .DST03+1
 INY
 STY  .SRC04+1
 STY  .DST04+1
 INY
 STY  .SRC05+1
 STY  .DST05+1
 INY
 STY  .SRC06+1
 STY  .DST06+1

 LDY  SC_LO+6,X
 STY  .SRC07+1
 STY  .DST07+1
 INY
 STY  .SRC08+1
 STY  .DST08+1
 INY
 STY  .SRC09+1
 STY  .DST09+1
 INY
 STY  .SRC10+1
 STY  .DST10+1
 INY
 STY  .SRC11+1
 STY  .DST11+1
 INY
 STY  .SRC12+1
 STY  .DST12+1
 INY
 STY  .SRC13+1
 STY  .DST13+1
 INY
 STY  .SRC14+1
 STY  .DST14+1

 LDY  SC_LO+14,X
 STY  .SRC15+1
 STY  .DST15+1
 INY
 STY  .SRC16+1
 STY  .DST16+1
 INY
 STY  .SRC17+1
 STY  .DST17+1
 INY
 STY  .SRC18+1
 STY  .DST18+1
 INY
 STY  .SRC19+1
 STY  .DST19+1
 INY
 STY  .SRC20+1
 STY  .DST20+1
 INY
 STY  .SRC21+1
 STY  .DST21+1
; INY
; STY  .SRC22+1
; STY  .DST22+1

; LDY  SC_LO+22,X
; STY  .SRC23+1
; STY  .DST23+1
; INY
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .SRC01+2
 STA  .DST01+2
 STA  .SRC02+2
 STA  .DST02+2
 STA  .SRC03+2
 STA  .DST03+2
 STA  .SRC04+2
 STA  .DST04+2
 STA  .SRC05+2
 STA  .DST05+2
 STA  .SRC06+2
 STA  .DST06+2

 LDA  SC_HI+6,X
 STA  .SRC07+2
 STA  .DST07+2
 STA  .SRC08+2
 STA  .DST08+2
 STA  .SRC09+2
 STA  .DST09+2
 STA  .SRC10+2
 STA  .DST10+2
 STA  .SRC11+2
 STA  .DST11+2
 STA  .SRC12+2
 STA  .DST12+2
 STA  .SRC13+2
 STA  .DST13+2
 STA  .SRC14+2
 STA  .DST14+2

 LDA  SC_HI+14,X
 STA  .SRC15+2
 STA  .DST15+2
 STA  .SRC16+2
 STA  .DST16+2
 STA  .SRC17+2
 STA  .DST17+2
 STA  .SRC18+2
 STA  .DST18+2
 STA  .SRC19+2
 STA  .DST19+2
 STA  .SRC20+2
 STA  .DST20+2
 STA  .SRC21+2
 STA  .DST21+2
; STA  .SRC22+2
; STA  .DST22+2

; LDA  SC_HI+22,X
; STA  .SRC23+2
; STA  .DST23+2
; STA  .SRC24+2
; STA  .DST24+2
 JMP .SETUP

.SPR_SCN_03
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1
 INY
 STY  .SRC02+1
 STY  .DST02+1
 INY
 STY  .SRC03+1
 STY  .DST03+1
 INY
 STY  .SRC04+1
 STY  .DST04+1
 INY
 STY  .SRC05+1
 STY  .DST05+1

 LDY  SC_LO+5,X
 STY  .SRC06+1
 STY  .DST06+1
 INY
 STY  .SRC07+1
 STY  .DST07+1
 INY
 STY  .SRC08+1
 STY  .DST08+1
 INY
 STY  .SRC09+1
 STY  .DST09+1
 INY
 STY  .SRC10+1
 STY  .DST10+1
 INY
 STY  .SRC11+1
 STY  .DST11+1
 INY
 STY  .SRC12+1
 STY  .DST12+1
 INY
 STY  .SRC13+1
 STY  .DST13+1

 LDY  SC_LO+13,X
 STY  .SRC14+1
 STY  .DST14+1
 INY
 STY  .SRC15+1
 STY  .DST15+1
 INY
 STY  .SRC16+1
 STY  .DST16+1
 INY
 STY  .SRC17+1
 STY  .DST17+1
 INY
 STY  .SRC18+1
 STY  .DST18+1
 INY
 STY  .SRC19+1
 STY  .DST19+1
 INY
 STY  .SRC20+1
 STY  .DST20+1
 INY
 STY  .SRC21+1
 STY  .DST21+1

; LDY  SC_LO+21,X
; STY  .SRC22+1
; STY  .DST22+1
; INY
; STY  .SRC23+1
; STY  .DST23+1
; INY
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .SRC01+2
 STA  .DST01+2
 STA  .SRC02+2
 STA  .DST02+2
 STA  .SRC03+2
 STA  .DST03+2
 STA  .SRC04+2
 STA  .DST04+2
 STA  .SRC05+2
 STA  .DST05+2

 LDA  SC_HI+5,X
 STA  .SRC06+2
 STA  .DST06+2
 STA  .SRC07+2
 STA  .DST07+2
 STA  .SRC08+2
 STA  .DST08+2
 STA  .SRC09+2
 STA  .DST09+2
 STA  .SRC10+2
 STA  .DST10+2
 STA  .SRC11+2
 STA  .DST11+2
 STA  .SRC12+2
 STA  .DST12+2
 STA  .SRC13+2
 STA  .DST13+2

 LDA  SC_HI+13,X
 STA  .SRC14+2
 STA  .DST14+2
 STA  .SRC15+2
 STA  .DST15+2
 STA  .SRC16+2
 STA  .DST16+2
 STA  .SRC17+2
 STA  .DST17+2
 STA  .SRC18+2
 STA  .DST18+2
 STA  .SRC19+2
 STA  .DST19+2
 STA  .SRC20+2
 STA  .DST20+2
 STA  .SRC21+2
 STA  .DST21+2

; LDA  SC_HI+21,X
; STA  .SRC22+2
; STA  .DST22+2
; STA  .SRC23+2
; STA  .DST23+2
; STA  .SRC24+2
; STA  .DST24+2
 JMP .SETUP

.SPR_SCN_04
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1
 INY
 STY  .SRC02+1
 STY  .DST02+1
 INY
 STY  .SRC03+1
 STY  .DST03+1
 INY
 STY  .SRC04+1
 STY  .DST04+1

 LDY  SC_LO+4,X
 STY  .SRC05+1
 STY  .DST05+1
 INY
 STY  .SRC06+1
 STY  .DST06+1
 INY
 STY  .SRC07+1
 STY  .DST07+1
 INY
 STY  .SRC08+1
 STY  .DST08+1
 INY
 STY  .SRC09+1
 STY  .DST09+1
 INY
 STY  .SRC10+1
 STY  .DST10+1
 INY
 STY  .SRC11+1
 STY  .DST11+1
 INY
 STY  .SRC12+1
 STY  .DST12+1

 LDY  SC_LO+12,X
 STY  .SRC13+1
 STY  .DST13+1
 INY
 STY  .SRC14+1
 STY  .DST14+1
 INY
 STY  .SRC15+1
 STY  .DST15+1
 INY
 STY  .SRC16+1
 STY  .DST16+1
 INY
 STY  .SRC17+1
 STY  .DST17+1
 INY
 STY  .SRC18+1
 STY  .DST18+1
 INY
 STY  .SRC19+1
 STY  .DST19+1
 INY
 STY  .SRC20+1
 STY  .DST20+1

 LDY  SC_LO+20,X
 STY  .SRC21+1
 STY  .DST21+1
; INY
; STY  .SRC22+1
; STY  .DST22+1
; INY
; STY  .SRC23+1
; STY  .DST23+1
; INY
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .SRC01+2
 STA  .DST01+2
 STA  .SRC02+2
 STA  .DST02+2
 STA  .SRC03+2
 STA  .DST03+2
 STA  .SRC04+2
 STA  .DST04+2

 LDA  SC_HI+4,X
 STA  .SRC05+2
 STA  .DST05+2
 STA  .SRC06+2
 STA  .DST06+2
 STA  .SRC07+2
 STA  .DST07+2
 STA  .SRC08+2
 STA  .DST08+2
 STA  .SRC09+2
 STA  .DST09+2
 STA  .SRC10+2
 STA  .DST10+2
 STA  .SRC11+2
 STA  .DST11+2
 STA  .SRC12+2
 STA  .DST12+2

 LDA  SC_HI+12,X
 STA  .SRC13+2
 STA  .DST13+2
 STA  .SRC14+2
 STA  .DST14+2
 STA  .SRC15+2
 STA  .DST15+2
 STA  .SRC16+2
 STA  .DST16+2
 STA  .SRC17+2
 STA  .DST17+2
 STA  .SRC18+2
 STA  .DST18+2
 STA  .SRC19+2
 STA  .DST19+2
 STA  .SRC20+2
 STA  .DST20+2

LDA  SC_HI+20,X
 STA  .SRC21+2
 STA  .DST21+2
; STA  .SRC22+2
; STA  .DST22+2
; STA  .SRC23+2
; STA  .DST23+2
; STA  .SRC24+2
; STA  .DST24+2
 JMP .SETUP

.SPR_SCN_05
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1
 INY
 STY  .SRC02+1
 STY  .DST02+1
 INY
 STY  .SRC03+1
 STY  .DST03+1

 LDY  SC_LO+3,X
 STY  .SRC04+1
 STY  .DST04+1
 INY
 STY  .SRC05+1
 STY  .DST05+1
 INY
 STY  .SRC06+1
 STY  .DST06+1
 INY
 STY  .SRC07+1
 STY  .DST07+1
 INY
 STY  .SRC08+1
 STY  .DST08+1
 INY
 STY  .SRC09+1
 STY  .DST09+1
 INY
 STY  .SRC10+1
 STY  .DST10+1
 INY
 STY  .SRC11+1
 STY  .DST11+1

 LDY  SC_LO+11,X
 STY  .SRC12+1
 STY  .DST12+1
 INY
 STY  .SRC13+1
 STY  .DST13+1
 INY
 STY  .SRC14+1
 STY  .DST14+1
 INY
 STY  .SRC15+1
 STY  .DST15+1
 INY
 STY  .SRC16+1
 STY  .DST16+1
 INY
 STY  .SRC17+1
 STY  .DST17+1
 INY
 STY  .SRC18+1
 STY  .DST18+1
 INY
 STY  .SRC19+1
 STY  .DST19+1

 LDY  SC_LO+19,X
 STY  .SRC20+1
 STY  .DST20+1
 INY
 STY  .SRC21+1
 STY  .DST21+1
; INY
; STY  .SRC22+1
; STY  .DST22+1
; INY
; STY  .SRC23+1
; STY  .DST23+1
; INY
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .SRC01+2
 STA  .DST01+2
 STA  .SRC02+2
 STA  .DST02+2
 STA  .SRC03+2
 STA  .DST03+2

 LDA  SC_HI+3,X
 STA  .SRC04+2
 STA  .DST04+2
 STA  .SRC05+2
 STA  .DST05+2
 STA  .SRC06+2
 STA  .DST06+2
 STA  .SRC07+2
 STA  .DST07+2
 STA  .SRC08+2
 STA  .DST08+2
 STA  .SRC09+2
 STA  .DST09+2
 STA  .SRC10+2
 STA  .DST10+2
 STA  .SRC11+2
 STA  .DST11+2

 LDA  SC_HI+11,X
 STA  .SRC12+2
 STA  .DST12+2
 STA  .SRC13+2
 STA  .DST13+2
 STA  .SRC14+2
 STA  .DST14+2
 STA  .SRC15+2
 STA  .DST15+2
 STA  .SRC16+2
 STA  .DST16+2
 STA  .SRC17+2
 STA  .DST17+2
 STA  .SRC18+2
 STA  .DST18+2
 STA  .SRC19+2
 STA  .DST19+2

 LDA  SC_HI+19,X
 STA  .SRC20+2
 STA  .DST20+2
 STA  .SRC21+2
 STA  .DST21+2
; STA  .SRC22+2
; STA  .DST22+2
; STA  .SRC23+2
; STA  .DST23+2
; STA  .SRC24+2
; STA  .DST24+2
 JMP .SETUP

.SPR_SCN_06
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1
 INY
 STY  .SRC02+1
 STY  .DST02+1

 LDY  SC_LO+2,X
 STY  .SRC03+1
 STY  .DST03+1
 INY
 STY  .SRC04+1
 STY  .DST04+1
 INY
 STY  .SRC05+1
 STY  .DST05+1
 INY
 STY  .SRC06+1
 STY  .DST06+1
 INY
 STY  .SRC07+1
 STY  .DST07+1
 INY
 STY  .SRC08+1
 STY  .DST08+1
 INY
 STY  .SRC09+1
 STY  .DST09+1
 INY
 STY  .SRC10+1
 STY  .DST10+1

 LDY  SC_LO+10,X
 STY  .SRC11+1
 STY  .DST11+1
 INY
 STY  .SRC12+1
 STY  .DST12+1
 INY
 STY  .SRC13+1
 STY  .DST13+1
 INY
 STY  .SRC14+1
 STY  .DST14+1
 INY
 STY  .SRC15+1
 STY  .DST15+1
 INY
 STY  .SRC16+1
 STY  .DST16+1
 INY
 STY  .SRC17+1
 STY  .DST17+1
 INY
 STY  .SRC18+1
 STY  .DST18+1

 LDY  SC_LO+18,X
 STY  .SRC19+1
 STY  .DST19+1
 INY
 STY  .SRC20+1
 STY  .DST20+1
 INY
 STY  .SRC21+1
 STY  .DST21+1
; INY
; STY  .SRC22+1
; STY  .DST22+1
; INY
; STY  .SRC23+1
; STY  .DST23+1
; INY
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .SRC01+2
 STA  .DST01+2
 STA  .SRC02+2
 STA  .DST02+2

 LDA  SC_HI+2,X
 STA  .SRC03+2
 STA  .DST03+2
 STA  .SRC04+2
 STA  .DST04+2
 STA  .SRC05+2
 STA  .DST05+2
 STA  .SRC06+2
 STA  .DST06+2
 STA  .SRC07+2
 STA  .DST07+2
 STA  .SRC08+2
 STA  .DST08+2
 STA  .SRC09+2
 STA  .DST09+2
 STA  .SRC10+2
 STA  .DST10+2

 LDA  SC_HI+10,X
 STA  .SRC11+2
 STA  .DST11+2
 STA  .SRC12+2
 STA  .DST12+2
 STA  .SRC13+2
 STA  .DST13+2
 STA  .SRC14+2
 STA  .DST14+2
 STA  .SRC15+2
 STA  .DST15+2
 STA  .SRC16+2
 STA  .DST16+2
 STA  .SRC17+2
 STA  .DST17+2
 STA  .SRC18+2
 STA  .DST18+2

 LDA  SC_HI+18,X
 STA  .SRC19+2
 STA  .DST19+2
 STA  .SRC20+2
 STA  .DST20+2
 STA  .SRC21+2
 STA  .DST21+2
; STA  .SRC22+2
; STA  .DST22+2
; STA  .SRC23+2
; STA  .DST23+2
; STA  .SRC24+2
; STA  .DST24+2
 JMP .SETUP

.SPR_SCN_07
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1

 LDY  SC_LO+1,X
 STY  .SRC02+1
 STY  .DST02+1
 INY
 STY  .SRC03+1
 STY  .DST03+1
 INY
 STY  .SRC04+1
 STY  .DST04+1
 INY
 STY  .SRC05+1
 STY  .DST05+1
 INY
 STY  .SRC06+1
 STY  .DST06+1
 INY
 STY  .SRC07+1
 STY  .DST07+1
 INY
 STY  .SRC08+1
 STY  .DST08+1
 INY
 STY  .SRC09+1
 STY  .DST09+1

 LDY  SC_LO+9,X
 STY  .SRC10+1
 STY  .DST10+1
 INY
 STY  .SRC11+1
 STY  .DST11+1
 INY
 STY  .SRC12+1
 STY  .DST12+1
 INY
 STY  .SRC13+1
 STY  .DST13+1
 INY
 STY  .SRC14+1
 STY  .DST14+1
 INY
 STY  .SRC15+1
 STY  .DST15+1
 INY
 STY  .SRC16+1
 STY  .DST16+1
 INY
 STY  .SRC17+1
 STY  .DST17+1

 LDY  SC_LO+17,X
 STY  .SRC18+1
 STY  .DST18+1
 INY
 STY  .SRC19+1
 STY  .DST19+1
 INY
 STY  .SRC20+1
 STY  .DST20+1
 INY
 STY  .SRC21+1
 STY  .DST21+1
; INY
; STY  .SRC22+1
; STY  .DST22+1
; INY
; STY  .SRC23+1
; STY  .DST23+1
; INY
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .SRC01+2
 STA  .DST01+2

 LDA  SC_HI+1,X
 STA  .SRC02+2
 STA  .DST02+2
 STA  .SRC03+2
 STA  .DST03+2
 STA  .SRC04+2
 STA  .DST04+2
 STA  .SRC05+2
 STA  .DST05+2
 STA  .SRC06+2
 STA  .DST06+2
 STA  .SRC07+2
 STA  .DST07+2
 STA  .SRC08+2
 STA  .DST08+2
 STA  .SRC09+2
 STA  .DST09+2

 LDA  SC_HI+9,X
 STA  .SRC10+2
 STA  .DST10+2
 STA  .SRC11+2
 STA  .DST11+2
 STA  .SRC12+2
 STA  .DST12+2
 STA  .SRC13+2
 STA  .DST13+2
 STA  .SRC14+2
 STA  .DST14+2
 STA  .SRC15+2
 STA  .DST15+2
 STA  .SRC16+2
 STA  .DST16+2
 STA  .SRC17+2
 STA  .DST17+2

 LDA  SC_HI+17,X
 STA  .SRC18+2
 STA  .DST18+2
 STA  .SRC19+2
 STA  .DST19+2
 STA  .SRC20+2
 STA  .DST20+2
 STA  .SRC21+2
 STA  .DST21+2
; STA  .SRC22+2
; STA  .DST22+2
; STA  .SRC23+2
; STA  .DST23+2
; STA  .SRC24+2
; STA  .DST24+2
; JMP .SETUP

.SETUP
 LDX REGX
 LDY SCR_TAB3,X
 LDX #48 ; 32 ; 48 ; SPR_CNT ; 24 16 8 0 (needs to be colums*rows)
; SEC

 INC $D020

.LOOP
.SRC01 LDA $ABCD,Y
.SPA01 AND $ABCD,X
.SPO01 ORA $ABCD,X
.DST01 STA $ABCD,Y

.SRC02 LDA $ABCD,Y
.SPA02 AND $ABCD,X
.SPO02 ORA $ABCD,X
.DST02 STA $ABCD,Y
     
.SRC03 LDA $ABCD,Y
.SPA03 AND $ABCD,X
.SPO03 ORA $ABCD,X
.DST03 STA $ABCD,Y

.SRC04 LDA $ABCD,Y
.SPA04 AND $ABCD,X
.SPO04 ORA $ABCD,X
.DST04 STA $ABCD,Y

.SRC05 LDA $ABCD,Y
.SPA05 AND $ABCD,X
.SPO05 ORA $ABCD,X
.DST05 STA $ABCD,Y

.SRC06 LDA $ABCD,Y
.SPA06 AND $ABCD,X
.SPO06 ORA $ABCD,X
.DST06 STA $ABCD,Y

.SRC07 LDA $ABCD,Y
.SPA07 AND $ABCD,X
.SPO07 ORA $ABCD,X
.DST07 STA $ABCD,Y

.SRC08 LDA $ABCD,Y
.SPA08 AND $ABCD,X
.SPO08 ORA $ABCD,X
.DST08 STA $ABCD,Y

.SRC09 LDA $ABCD,Y
.SPA09 AND $ABCD,X
.SPO09 ORA $ABCD,X
.DST09 STA $ABCD,Y

.SRC10 LDA $ABCD,Y
.SPA10 AND $ABCD,X
.SPO10 ORA $ABCD,X
.DST10 STA $ABCD,Y

.SRC11 LDA $ABCD,Y
.SPA11 AND $ABCD,X
.SPO11 ORA $ABCD,X
.DST11 STA $ABCD,Y

.SRC12 LDA $ABCD,Y
.SPA12 AND $ABCD,X
.SPO12 ORA $ABCD,X
.DST12 STA $ABCD,Y

.SRC13 LDA $ABCD,Y
.SPA13 AND $ABCD,X
.SPO13 ORA $ABCD,X
.DST13 STA $ABCD,Y

.SRC14 LDA $ABCD,Y
.SPA14 AND $ABCD,X
.SPO14 ORA $ABCD,X
.DST14 STA $ABCD,Y

.SRC15 LDA $ABCD,Y
.SPA15 AND $ABCD,X
.SPO15 ORA $ABCD,X
.DST15 STA $ABCD,Y

.SRC16 LDA $ABCD,Y
.SPA16 AND $ABCD,X
.SPO16 ORA $ABCD,X
.DST16 STA $ABCD,Y

.SRC17 LDA $ABCD,Y
.SPA17 AND $ABCD,X
.SPO17 ORA $ABCD,X
.DST17 STA $ABCD,Y

.SRC18 LDA $ABCD,Y
.SPA18 AND $ABCD,X
.SPO18 ORA $ABCD,X
.DST18 STA $ABCD,Y

.SRC19 LDA $ABCD,Y
.SPA19 AND $ABCD,X
.SPO19 ORA $ABCD,X
.DST19 STA $ABCD,Y

.SRC20 LDA $ABCD,Y
.SPA20 AND $ABCD,X
.SPO20 ORA $ABCD,X
.DST20 STA $ABCD,Y

.SRC21 LDA $ABCD,Y
.SPA21 AND $ABCD,X
.SPO21 ORA $ABCD,X
.DST21 STA $ABCD,Y

;.SRC22 LDA $ABCD,Y
;.SPA22 AND $ABCD,X
;.SPO22 ORA $ABCD,X
;.DST22 STA $ABCD,Y

;.SRC23 LDA $ABCD,Y
;.SPA23 AND $ABCD,X
;.SPO23 ORA $ABCD,X
;.DST23 STA $ABCD,Y

;.SRC24 LDA $ABCD,Y
;.SPA24 AND $ABCD,X
;.SPO24 ORA $ABCD,X
;.DST24 STA $ABCD,Y

;  TYA
;  ADC #7 ; #8-1 ; carry set
;  TAY

  LDA #$FF
  SBX #24 ; = x=x-24 ; #$fc ;equivalent to +4 - sets the carry flag?
  BMI .EXIT 
    TYA
    ADC #7 ; #8-1 ; carry set
    TAY
    JMP .LOOP

.EXIT  
 INC $D020

RTS

!ZONE BAK_SCN
BAK_SCN ; a=ver / y=hor / x=sprite

 INC $D020
 STY REGY
 AND #7
 ASL
 STA .JMP +1
.JMP JMP (BAK_SCN_TAB)

.BAK_SCN_00
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1
 INY
 STY  .SRC02+1
 STY  .DST02+1
 INY
 STY  .SRC03+1
 STY  .DST03+1
 INY
 STY  .SRC04+1
 STY  .DST04+1
 INY
 STY  .SRC05+1
 STY  .DST05+1
 INY
 STY  .SRC06+1
 STY  .DST06+1
 INY
 STY  .SRC07+1
 STY  .DST07+1
 INY
 STY  .SRC08+1
 STY  .DST08+1
 LDY  SC_LO+8,X
 STY  .SRC09+1
 STY  .DST09+1
 INY
 STY  .SRC10+1
 STY  .DST10+1
 INY
 STY  .SRC11+1
 STY  .DST11+1
 INY
 STY  .SRC12+1
 STY  .DST12+1
 INY
 STY  .SRC13+1
 STY  .DST13+1
 INY
 STY  .SRC14+1
 STY  .DST14+1
 INY
 STY  .SRC15+1
 STY  .DST15+1
 INY
 STY  .SRC16+1
 STY  .DST16+1
 LDY  SC_LO+16,X
 STY  .SRC17+1
 STY  .DST17+1
 INY
 STY  .SRC18+1
 STY  .DST18+1
 INY
 STY  .SRC19+1
 STY  .DST19+1
 INY
 STY  .SRC20+1
 STY  .DST20+1
 INY
 STY  .SRC21+1
 STY  .DST21+1
; INY
; STY  .SRC22+1
; STY  .DST22+1
; INY
; STY  .SRC23+1
; STY  .DST23+1
; INY
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .DST01+2
 STA  .DST02+2
 STA  .DST03+2
 STA  .DST04+2
 STA  .DST05+2
 STA  .DST06+2
 STA  .DST07+2
 STA  .DST08+2
 ORA  #128
 STA  .SRC01+2
 STA  .SRC02+2
 STA  .SRC03+2
 STA  .SRC04+2
 STA  .SRC05+2
 STA  .SRC06+2
 STA  .SRC07+2
 STA  .SRC08+2
 LDA  SC_HI+8,X 
 STA  .DST09+2
 STA  .DST10+2
 STA  .DST11+2
 STA  .DST12+2
 STA  .DST13+2
 STA  .DST14+2
 STA  .DST15+2
 STA  .DST16+2
 ORA  #128
 STA  .SRC09+2
 STA  .SRC10+2
 STA  .SRC11+2
 STA  .SRC12+2
 STA  .SRC13+2
 STA  .SRC14+2
 STA  .SRC15+2
 STA  .SRC16+2
 LDA  SC_HI+16,X 
 STA  .DST17+2
 STA  .DST18+2
 STA  .DST19+2
 STA  .DST20+2
 STA  .DST21+2
; STA  .DST22+2
; STA  .DST23+2
; STA  .DST24+2
 ORA  #128
 STA  .SRC17+2
 STA  .SRC18+2
 STA  .SRC19+2
 STA  .SRC20+2
 STA  .SRC21+2
; STA  .SRC22+2
; STA  .SRC23+2
; STA  .SRC24+2
 JMP .SETUP

.BAK_SCN_01
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1
 INY
 STY  .SRC02+1
 STY  .DST02+1
 INY
 STY  .SRC03+1
 STY  .DST03+1
 INY
 STY  .SRC04+1
 STY  .DST04+1
 INY
 STY  .SRC05+1
 STY  .DST05+1
 INY
 STY  .SRC06+1
 STY  .DST06+1
 INY
 STY  .SRC07+1
 STY  .DST07+1

 LDY  SC_LO+7,X
 STY  .SRC08+1
 STY  .DST08+1
 INY
 STY  .SRC09+1
 STY  .DST09+1
 INY
 STY  .SRC10+1
 STY  .DST10+1
 INY
 STY  .SRC11+1
 STY  .DST11+1
 INY
 STY  .SRC12+1
 STY  .DST12+1
 INY
 STY  .SRC13+1
 STY  .DST13+1
 INY
 STY  .SRC14+1
 STY  .DST14+1
 INY
 STY  .SRC15+1
 STY  .DST15+1

 LDY  SC_LO+15,X
 STY  .SRC16+1
 STY  .DST16+1
 INY
 STY  .SRC17+1
 STY  .DST17+1
 INY
 STY  .SRC18+1
 STY  .DST18+1
 INY
 STY  .SRC19+1
 STY  .DST19+1
 INY
 STY  .SRC20+1
 STY  .DST20+1
 INY
 STY  .SRC21+1
 STY  .DST21+1
; INY
; STY  .SRC22+1
; STY  .DST22+1
; INY
; STY  .SRC23+1
; STY  .DST23+1

; LDY  SC_LO+23,X
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .DST01+2
 STA  .DST02+2
 STA  .DST03+2
 STA  .DST04+2
 STA  .DST05+2
 STA  .DST06+2
 STA  .DST07+2
 ORA  #128
 STA  .SRC01+2
 STA  .SRC02+2
 STA  .SRC03+2
 STA  .SRC04+2
 STA  .SRC05+2
 STA  .SRC06+2
 STA  .SRC07+2

 LDA  SC_HI+7,X 
 STA  .DST08+2
 STA  .DST09+2
 STA  .DST10+2
 STA  .DST11+2
 STA  .DST12+2
 STA  .DST13+2
 STA  .DST14+2
 STA  .DST15+2
 ORA  #128
 STA  .SRC08+2
 STA  .SRC09+2
 STA  .SRC10+2
 STA  .SRC11+2
 STA  .SRC12+2
 STA  .SRC13+2
 STA  .SRC14+2
 STA  .SRC15+2

 LDA  SC_HI+15,X
 STA  .DST16+2
 STA  .DST17+2
 STA  .DST18+2
 STA  .DST19+2
 STA  .DST20+2
; STA  .DST21+2
; STA  .DST22+2
; STA  .DST23+2
 ORA  #128
 STA  .SRC16+2
 STA  .SRC17+2
 STA  .SRC18+2
 STA  .SRC19+2
 STA  .SRC20+2
; STA  .SRC21+2
; STA  .SRC22+2
; STA  .SRC23+2

; LDA  SC_HI+23,X
; STA  .DST24+2
; ORA  #128
; STA  .SRC24+2
 JMP .SETUP

.BAK_SCN_02
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1
 INY
 STY  .SRC02+1
 STY  .DST02+1
 INY
 STY  .SRC03+1
 STY  .DST03+1
 INY
 STY  .SRC04+1
 STY  .DST04+1
 INY
 STY  .SRC05+1
 STY  .DST05+1
 INY
 STY  .SRC06+1
 STY  .DST06+1

 LDY  SC_LO+6,X
 STY  .SRC07+1
 STY  .DST07+1
 INY
 STY  .SRC08+1
 STY  .DST08+1
 INY
 STY  .SRC09+1
 STY  .DST09+1
 INY
 STY  .SRC10+1
 STY  .DST10+1
 INY
 STY  .SRC11+1
 STY  .DST11+1
 INY
 STY  .SRC12+1
 STY  .DST12+1
 INY
 STY  .SRC13+1
 STY  .DST13+1
 INY
 STY  .SRC14+1
 STY  .DST14+1

 LDY  SC_LO+14,X
 STY  .SRC15+1
 STY  .DST15+1
 INY
 STY  .SRC16+1
 STY  .DST16+1
 INY
 STY  .SRC17+1
 STY  .DST17+1
 INY
 STY  .SRC18+1
 STY  .DST18+1
 INY
 STY  .SRC19+1
 STY  .DST19+1
 INY
 STY  .SRC20+1
 STY  .DST20+1
 INY
 STY  .SRC21+1
 STY  .DST21+1
; INY
; STY  .SRC22+1
; STY  .DST22+1

; LDY  SC_LO+22,X
; STY  .SRC23+1
; STY  .DST23+1
; INY
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .DST01+2
 STA  .DST02+2
 STA  .DST03+2
 STA  .DST04+2
 STA  .DST05+2
 STA  .DST06+2
 ORA  #128
 STA  .SRC01+2
 STA  .SRC02+2
 STA  .SRC03+2
 STA  .SRC04+2
 STA  .SRC05+2
 STA  .SRC06+2

 LDA  SC_HI+6,X
 STA  .DST07+2
 STA  .DST08+2
 STA  .DST09+2
 STA  .DST10+2
 STA  .DST11+2
 STA  .DST12+2
 STA  .DST13+2
 STA  .DST14+2
 ORA  #128
 STA  .SRC07+2
 STA  .SRC08+2
 STA  .SRC09+2
 STA  .SRC10+2
 STA  .SRC11+2
 STA  .SRC12+2
 STA  .SRC13+2
 STA  .SRC14+2

 LDA  SC_HI+14,X
 STA  .DST15+2
 STA  .DST16+2
 STA  .DST17+2
 STA  .DST18+2
 STA  .DST19+2
 STA  .DST20+2
 STA  .DST21+2
; STA  .DST22+2
 ORA  #128
 STA  .SRC15+2
 STA  .SRC16+2
 STA  .SRC17+2
 STA  .SRC18+2
 STA  .SRC19+2
 STA  .SRC20+2
 STA  .SRC21+2
; STA  .SRC22+2

; LDA  SC_HI+22,X
; STA  .DST23+2
; STA  .DST24+2
; ORA  #128
; STA  .SRC23+2
; STA  .SRC24+2
 JMP .SETUP

.BAK_SCN_03
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1
 INY
 STY  .SRC02+1
 STY  .DST02+1
 INY
 STY  .SRC03+1
 STY  .DST03+1
 INY
 STY  .SRC04+1
 STY  .DST04+1
 INY
 STY  .SRC05+1
 STY  .DST05+1

 LDY  SC_LO+5,X
 STY  .SRC06+1
 STY  .DST06+1
 INY
 STY  .SRC07+1
 STY  .DST07+1
 INY
 STY  .SRC08+1
 STY  .DST08+1
 INY
 STY  .SRC09+1
 STY  .DST09+1
 INY
 STY  .SRC10+1
 STY  .DST10+1
 INY
 STY  .SRC11+1
 STY  .DST11+1
 INY
 STY  .SRC12+1
 STY  .DST12+1
 INY
 STY  .SRC13+1
 STY  .DST13+1

 LDY  SC_LO+13,X
 STY  .SRC14+1
 STY  .DST14+1
 INY
 STY  .SRC15+1
 STY  .DST15+1
 INY
 STY  .SRC16+1
 STY  .DST16+1
 INY
 STY  .SRC17+1
 STY  .DST17+1
 INY
 STY  .SRC18+1
 STY  .DST18+1
 INY
 STY  .SRC19+1
 STY  .DST19+1
 INY
 STY  .SRC20+1
 STY  .DST20+1
 INY
 STY  .SRC21+1
 STY  .DST21+1

; LDY  SC_LO+21,X
; STY  .SRC22+1
; STY  .DST22+1
; INY
; STY  .SRC23+1
; STY  .DST23+1
; INY
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .DST01+2
 STA  .DST02+2
 STA  .DST03+2
 STA  .DST04+2
 STA  .DST05+2
 ORA  #128
 STA  .SRC01+2
 STA  .SRC02+2
 STA  .SRC03+2
 STA  .SRC04+2
 STA  .SRC05+2

 LDA  SC_HI+5,X
 STA  .DST06+2
 STA  .DST07+2
 STA  .DST08+2
 STA  .DST09+2
 STA  .DST10+2
 STA  .DST11+2
 STA  .DST12+2
 STA  .DST13+2
 ORA  #128
 STA  .SRC06+2
 STA  .SRC07+2
 STA  .SRC08+2
 STA  .SRC09+2
 STA  .SRC10+2
 STA  .SRC11+2
 STA  .SRC12+2
 STA  .SRC13+2

 LDA  SC_HI+13,X
 STA  .DST14+2
 STA  .DST15+2
 STA  .DST16+2
 STA  .DST17+2
 STA  .DST18+2
 STA  .DST19+2
 STA  .DST20+2
 STA  .DST21+2
 ORA  #128
 STA  .SRC14+2
 STA  .SRC15+2
 STA  .SRC16+2
 STA  .SRC17+2
 STA  .SRC18+2
 STA  .SRC19+2
 STA  .SRC20+2
 STA  .SRC21+2

; LDA  SC_HI+21,X
; STA  .DST22+2
; STA  .DST23+2
; STA  .DST24+2
; ORA  #128
; STA  .SRC22+2
; STA  .SRC23+2
; STA  .SRC24+2
 JMP .SETUP

.BAK_SCN_04
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1
 INY
 STY  .SRC02+1
 STY  .DST02+1
 INY
 STY  .SRC03+1
 STY  .DST03+1
 INY
 STY  .SRC04+1
 STY  .DST04+1

 LDY  SC_LO+4,X
 STY  .SRC05+1
 STY  .DST05+1
 INY
 STY  .SRC06+1
 STY  .DST06+1
 INY
 STY  .SRC07+1
 STY  .DST07+1
 INY
 STY  .SRC08+1
 STY  .DST08+1
 INY
 STY  .SRC09+1
 STY  .DST09+1
 INY
 STY  .SRC10+1
 STY  .DST10+1
 INY
 STY  .SRC11+1
 STY  .DST11+1
 INY
 STY  .SRC12+1
 STY  .DST12+1

 LDY  SC_LO+12,X
 STY  .SRC13+1
 STY  .DST13+1
 INY
 STY  .SRC14+1
 STY  .DST14+1
 INY
 STY  .SRC15+1
 STY  .DST15+1
 INY
 STY  .SRC16+1
 STY  .DST16+1
 INY
 STY  .SRC17+1
 STY  .DST17+1
 INY
 STY  .SRC18+1
 STY  .DST18+1
 INY
 STY  .SRC19+1
 STY  .DST19+1
 INY
 STY  .SRC20+1
 STY  .DST20+1

 LDY  SC_LO+20,X
 STY  .SRC21+1
 STY  .DST21+1
; INY
; STY  .SRC22+1
; STY  .DST22+1
; INY
; STY  .SRC23+1
; STY  .DST23+1
; INY
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .DST01+2
 STA  .DST02+2
 STA  .DST03+2
 STA  .DST04+2
 ORA  #128
 STA  .SRC01+2
 STA  .SRC02+2
 STA  .SRC03+2
 STA  .SRC04+2

 LDA  SC_HI+4,X
 STA  .DST05+2
 STA  .DST06+2
 STA  .DST07+2
 STA  .DST08+2
 STA  .DST09+2
 STA  .DST10+2
 STA  .DST11+2
 STA  .DST12+2
 ORA  #128
 STA  .SRC05+2
 STA  .SRC06+2
 STA  .SRC07+2
 STA  .SRC08+2
 STA  .SRC09+2
 STA  .SRC10+2
 STA  .SRC11+2
 STA  .SRC12+2

 LDA  SC_HI+12,X
 STA  .DST13+2
 STA  .DST14+2
 STA  .DST15+2
 STA  .DST16+2
 STA  .DST17+2
 STA  .DST18+2
 STA  .DST19+2
 STA  .DST20+2
 ORA  #128
 STA  .SRC13+2
 STA  .SRC14+2
 STA  .SRC15+2
 STA  .SRC16+2
 STA  .SRC17+2
 STA  .SRC18+2
 STA  .SRC19+2
 STA  .SRC20+2

 LDA  SC_HI+20,X
 STA  .DST21+2
; STA  .DST22+2
; STA  .DST23+2
; STA  .DST24+2
 ORA  #128
 STA  .SRC21+2
; STA  .SRC22+2
; STA  .SRC23+2
; STA  .SRC24+2
 JMP .SETUP

; todo

.BAK_SCN_05
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1
 INY
 STY  .SRC02+1
 STY  .DST02+1
 INY
 STY  .SRC03+1
 STY  .DST03+1

 LDY  SC_LO+3,X
 STY  .SRC04+1
 STY  .DST04+1
 INY
 STY  .SRC05+1
 STY  .DST05+1
 INY
 STY  .SRC06+1
 STY  .DST06+1
 INY
 STY  .SRC07+1
 STY  .DST07+1
 INY
 STY  .SRC08+1
 STY  .DST08+1
 INY
 STY  .SRC09+1
 STY  .DST09+1
 INY
 STY  .SRC10+1
 STY  .DST10+1
 INY
 STY  .SRC11+1
 STY  .DST11+1

 LDY  SC_LO+11,X
 STY  .SRC12+1
 STY  .DST12+1
 INY
 STY  .SRC13+1
 STY  .DST13+1
 INY
 STY  .SRC14+1
 STY  .DST14+1
 INY
 STY  .SRC15+1
 STY  .DST15+1
 INY
 STY  .SRC16+1
 STY  .DST16+1
 INY
 STY  .SRC17+1
 STY  .DST17+1
 INY
 STY  .SRC18+1
 STY  .DST18+1
 INY
 STY  .SRC19+1
 STY  .DST19+1

 LDY  SC_LO+19,X
 STY  .SRC20+1
 STY  .DST20+1
 INY
 STY  .SRC21+1
 STY  .DST21+1
; INY
; STY  .SRC22+1
; STY  .DST22+1
; INY
; STY  .SRC23+1
; STY  .DST23+1
; INY
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .DST01+2
 STA  .DST02+2
 STA  .DST03+2
 ORA  #128
 STA  .SRC01+2
 STA  .SRC02+2
 STA  .SRC03+2

 LDA  SC_HI+3,X
 STA  .DST04+2
 STA  .DST05+2
 STA  .DST06+2
 STA  .DST07+2
 STA  .DST08+2
 STA  .DST09+2
 STA  .DST10+2
 STA  .DST11+2
 ORA  #128
 STA  .SRC04+2
 STA  .SRC05+2
 STA  .SRC06+2
 STA  .SRC07+2
 STA  .SRC08+2
 STA  .SRC09+2
 STA  .SRC10+2
 STA  .SRC11+2

 LDA  SC_HI+11,X
 STA  .DST12+2
 STA  .DST13+2
 STA  .DST14+2
 STA  .DST15+2
 STA  .DST16+2
 STA  .DST17+2
 STA  .DST18+2
 STA  .DST19+2
 ORA  #128
 STA  .SRC12+2
 STA  .SRC13+2
 STA  .SRC14+2
 STA  .SRC15+2
 STA  .SRC16+2
 STA  .SRC17+2
 STA  .SRC18+2
 STA  .SRC19+2

 LDA  SC_HI+19,X
 STA  .DST20+2
 STA  .DST21+2
; STA  .DST22+2
; STA  .DST23+2
; STA  .DST24+2
 ORA  #128
 STA  .SRC20+2
 STA  .SRC21+2
; STA  .SRC22+2
; STA  .SRC23+2
; STA  .SRC24+2

 JMP .SETUP

.BAK_SCN_06
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1
 INY
 STY  .SRC02+1
 STY  .DST02+1

 LDY  SC_LO+2,X
 STY  .SRC03+1
 STY  .DST03+1
 INY
 STY  .SRC04+1
 STY  .DST04+1
 INY
 STY  .SRC05+1
 STY  .DST05+1
 INY
 STY  .SRC06+1
 STY  .DST06+1
 INY
 STY  .SRC07+1
 STY  .DST07+1
 INY
 STY  .SRC08+1
 STY  .DST08+1
 INY
 STY  .SRC09+1
 STY  .DST09+1
 INY
 STY  .SRC10+1
 STY  .DST10+1

 LDY  SC_LO+10,X
 STY  .SRC11+1
 STY  .DST11+1
 INY
 STY  .SRC12+1
 STY  .DST12+1
 INY
 STY  .SRC13+1
 STY  .DST13+1
 INY
 STY  .SRC14+1
 STY  .DST14+1
 INY
 STY  .SRC15+1
 STY  .DST15+1
 INY
 STY  .SRC16+1
 STY  .DST16+1
 INY
 STY  .SRC17+1
 STY  .DST17+1
 INY
 STY  .SRC18+1
 STY  .DST18+1

 LDY  SC_LO+18,X
 STY  .SRC19+1
 STY  .DST19+1
 INY
 STY  .SRC20+1
 STY  .DST20+1
 INY
 STY  .SRC21+1
 STY  .DST21+1
; INY
; STY  .SRC22+1
; STY  .DST22+1
; INY
; STY  .SRC23+1
; STY  .DST23+1
; INY
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .DST01+2
 STA  .DST02+2
 ORA  #128
 STA  .SRC01+2
 STA  .SRC02+2

 LDA  SC_HI+2,X
 STA  .DST03+2
 STA  .DST04+2
 STA  .DST05+2
 STA  .DST06+2
 STA  .DST07+2
 STA  .DST08+2
 STA  .DST09+2
 STA  .DST10+2
 ORA  #128
 STA  .SRC03+2
 STA  .SRC04+2
 STA  .SRC05+2
 STA  .SRC06+2
 STA  .SRC07+2
 STA  .SRC08+2
 STA  .SRC09+2
 STA  .SRC10+2

 LDA  SC_HI+10,X
 STA  .DST11+2
 STA  .DST12+2
 STA  .DST13+2
 STA  .DST14+2
 STA  .DST15+2
 STA  .DST16+2
 STA  .DST17+2
 STA  .DST18+2
 ORA  #128
 STA  .SRC11+2
 STA  .SRC12+2
 STA  .SRC13+2
 STA  .SRC14+2
 STA  .SRC15+2
 STA  .SRC16+2
 STA  .SRC17+2
 STA  .SRC18+2

 LDA  SC_HI+18,X
 STA  .DST19+2
 STA  .DST20+2
 STA  .DST21+2
; STA  .DST22+2
; STA  .DST23+2
; STA  .DST24+2
 ORA  #128
 STA  .SRC19+2
 STA  .SRC20+2
 STA  .SRC21+2
; STA  .SRC22+2
; STA  .SRC23+2
; STA  .SRC24+2
 JMP .SETUP

.BAK_SCN_07
 LDY  SC_LO+0,X
 STY  .SRC01+1
 STY  .DST01+1

 LDY  SC_LO+1,X
 STY  .SRC02+1
 STY  .DST02+1
 INY
 STY  .SRC03+1
 STY  .DST03+1
 INY
 STY  .SRC04+1
 STY  .DST04+1
 INY
 STY  .SRC05+1
 STY  .DST05+1
 INY
 STY  .SRC06+1
 STY  .DST06+1
 INY
 STY  .SRC07+1
 STY  .DST07+1
 INY
 STY  .SRC08+1
 STY  .DST08+1
 INY
 STY  .SRC09+1
 STY  .DST09+1

 LDY  SC_LO+9,X
 STY  .SRC10+1
 STY  .DST10+1
 INY
 STY  .SRC11+1
 STY  .DST11+1
 INY
 STY  .SRC12+1
 STY  .DST12+1
 INY
 STY  .SRC13+1
 STY  .DST13+1
 INY
 STY  .SRC14+1
 STY  .DST14+1
 INY
 STY  .SRC15+1
 STY  .DST15+1
 INY
 STY  .SRC16+1
 STY  .DST16+1
 INY
 STY  .SRC17+1
 STY  .DST17+1

 LDY  SC_LO+17,X
 STY  .SRC18+1
 STY  .DST18+1
 INY
 STY  .SRC19+1
 STY  .DST19+1
 INY
 STY  .SRC20+1
 STY  .DST20+1
 INY
 STY  .SRC21+1
 STY  .DST21+1
; INY
; STY  .SRC22+1
; STY  .DST22+1
; INY
; STY  .SRC23+1
; STY  .DST23+1
; INY
; STY  .SRC24+1
; STY  .DST24+1

 LDA  SC_HI+0,X 
 STA  .DST01+2
 ORA  #128
 STA  .SRC01+2

 LDA  SC_HI+1,X
 STA  .DST02+2
 STA  .DST03+2
 STA  .DST04+2
 STA  .DST05+2
 STA  .DST06+2
 STA  .DST07+2
 STA  .DST08+2
 STA  .DST09+2
 ORA  #128
 STA  .SRC02+2
 STA  .SRC03+2
 STA  .SRC04+2
 STA  .SRC05+2
 STA  .SRC06+2
 STA  .SRC07+2
 STA  .SRC08+2
 STA  .SRC09+2

 LDA  SC_HI+9,X
 STA  .DST10+2
 STA  .DST11+2
 STA  .DST12+2
 STA  .DST13+2
 STA  .DST14+2
 STA  .DST15+2
 STA  .DST16+2
 STA  .DST17+2
 ORA  #128
 STA  .SRC10+2
 STA  .SRC11+2
 STA  .SRC12+2
 STA  .SRC13+2
 STA  .SRC14+2
 STA  .SRC15+2
 STA  .SRC16+2
 STA  .SRC17+2

 LDA  SC_HI+17,X
 STA  .DST18+2
 STA  .DST19+2
 STA  .DST20+2
 STA  .DST21+2
; STA  .DST22+2
; STA  .DST23+2
; STA  .DST24+2
 ORA  #128
 STA  .SRC18+2
 STA  .SRC19+2
 STA  .SRC20+2
 STA  .SRC21+2
; STA  .SRC22+2
; STA  .SRC23+2
; STA  .SRC24+2
; JMP .SETUP

.SETUP
 ldy REGY
 LDX SCR_TAB3,Y
 LDY #2 ; SPR_CNT
 
.LOOP

;.SRC24  LDA $ABCD,x ;Y
;.DST24  STA $ABCD,x ;Y
;.SRC23  LDA $ABCD,x ;Y
;.DST23  STA $ABCD,x ;Y
;.SRC22  LDA $ABCD,x ;Y
;.DST22  STA $ABCD,x ;Y
.SRC21  LDA $ABCD,x ;Y
.DST21  STA $ABCD,x ;Y
.SRC20  LDA $ABCD,x ;Y
.DST20  STA $ABCD,x ;Y
.SRC19  LDA $ABCD,x ;Y
.DST19  STA $ABCD,x ;Y
.SRC18  LDA $ABCD,x ;Y
.DST18  STA $ABCD,x ;Y
.SRC17  LDA $ABCD,x ;Y
.DST17  STA $ABCD,x ;Y

.SRC16  LDA $ABCD,x ;Y
.DST16  STA $ABCD,x ;Y
.SRC15  LDA $ABCD,x ;Y
.DST15  STA $ABCD,x ;Y
.SRC14  LDA $ABCD,x ;Y
.DST14  STA $ABCD,x ;Y
.SRC13  LDA $ABCD,x ;Y
.DST13  STA $ABCD,x ;Y
.SRC12  LDA $ABCD,x ;Y
.DST12  STA $ABCD,x ;Y
.SRC11  LDA $ABCD,x ;Y
.DST11  STA $ABCD,x ;Y
.SRC10  LDA $ABCD,x ;Y
.DST10  STA $ABCD,x ;Y
.SRC09  LDA $ABCD,x ;Y
.DST09  STA $ABCD,x ;Y

.SRC08  LDA $ABCD,x ;Y
.DST08  STA $ABCD,x ;Y
.SRC07  LDA $ABCD,x ;Y
.DST07  STA $ABCD,x ;Y
.SRC06  LDA $ABCD,x ;Y
.DST06  STA $ABCD,x ;Y
.SRC05  LDA $ABCD,x ;Y
.DST05  STA $ABCD,x ;Y
.SRC04  LDA $ABCD,x ;Y
.DST04  STA $ABCD,x ;Y
.SRC03  LDA $ABCD,x ;Y
.DST03  STA $ABCD,x ;Y
.SRC02  LDA $ABCD,x ;Y
.DST02  STA $ABCD,x ;Y
.SRC01  LDA $ABCD,x ;Y
.DST01  STA $ABCD,x ;Y

  DEY
  BMI .EXIT

    LDA #$FF
    AXS #-8 ; = x=x+8
    JMP .LOOP

.EXIT

 DEC $D020
RTS

PATTERN
; !BYTE %00000000,%00010001,%00100010,%00110011,%01000100,%01010101,%01100110,%01110111,%10001000,%10011001,%10101010,%10111011,%11001100,%11011101,%11101110,%11111111
 !BYTE %00000000,%01010101,%10101010,%11111111
 !BYTE %00000000,%01010101,%10101010,%11111111
 !BYTE %00000000,%01010101,%10101010,%11111111
 !BYTE %00000000,%01010101,%10101010,%11111111

SCR_TAB3:
!BYTE $00,$00,$00,$00,$08,$08,$08,$08,$10,$10,$10,$10,$18,$18,$18,$18
!BYTE $20,$20,$20,$20,$28,$28,$28,$28,$30,$30,$30,$30,$38,$38,$38,$38
!BYTE $40,$40,$40,$40,$48,$48,$48,$48,$50,$50,$50,$50,$58,$58,$58,$58
!BYTE $60,$60,$60,$60,$68,$68,$68,$68,$70,$70,$70,$70,$78,$78,$78,$78
!BYTE $80,$80,$80,$80,$88,$88,$88,$88,$90,$90,$90,$90,$98,$98,$98,$98
!BYTE $A0,$A0,$A0,$A0,$A8,$A8,$A8,$A8,$B0,$B0,$B0,$B0,$B8,$B8,$B8,$B8
!BYTE $C0,$C0,$C0,$C0,$C8,$C8,$C8,$C8,$D0,$D0,$D0,$D0,$D8,$D8,$D8,$D8
!BYTE $E0,$E0,$E0,$E0,$E8,$E8,$E8,$E8,$F0,$F0,$F0,$F0,$F8,$F8,$F8,$F8

!align 255,0
BAK_SCN_TAB !WORD BAK_SCN.BAK_SCN_00, BAK_SCN.BAK_SCN_01, BAK_SCN.BAK_SCN_02, BAK_SCN.BAK_SCN_03, BAK_SCN.BAK_SCN_04, BAK_SCN.BAK_SCN_05, BAK_SCN.BAK_SCN_06, BAK_SCN.BAK_SCN_07  
SC_HI:
!BYTE >(SCN+(00*320)+0),>(SCN+(00*320)+1),>(SCN+(00*320)+2),>(SCN+(00*320)+3),>(SCN+(00*320)+4),>(SCN+(00*320)+5),>(SCN+(00*320)+6),>(SCN+(00*320)+7)
!BYTE >(SCN+(01*320)+0),>(SCN+(01*320)+1),>(SCN+(01*320)+2),>(SCN+(01*320)+3),>(SCN+(01*320)+4),>(SCN+(01*320)+5),>(SCN+(01*320)+6),>(SCN+(01*320)+7)
!BYTE >(SCN+(02*320)+0),>(SCN+(02*320)+1),>(SCN+(02*320)+2),>(SCN+(02*320)+3),>(SCN+(02*320)+4),>(SCN+(02*320)+5),>(SCN+(02*320)+6),>(SCN+(02*320)+7)
!BYTE >(SCN+(03*320)+0),>(SCN+(03*320)+1),>(SCN+(03*320)+2),>(SCN+(03*320)+3),>(SCN+(03*320)+4),>(SCN+(03*320)+5),>(SCN+(03*320)+6),>(SCN+(03*320)+7)
!BYTE >(SCN+(04*320)+0),>(SCN+(04*320)+1),>(SCN+(04*320)+2),>(SCN+(04*320)+3),>(SCN+(04*320)+4),>(SCN+(04*320)+5),>(SCN+(04*320)+6),>(SCN+(04*320)+7)
!BYTE >(SCN+(05*320)+0),>(SCN+(05*320)+1),>(SCN+(05*320)+2),>(SCN+(05*320)+3),>(SCN+(05*320)+4),>(SCN+(05*320)+5),>(SCN+(05*320)+6),>(SCN+(05*320)+7)
!BYTE >(SCN+(06*320)+0),>(SCN+(06*320)+1),>(SCN+(06*320)+2),>(SCN+(06*320)+3),>(SCN+(06*320)+4),>(SCN+(06*320)+5),>(SCN+(06*320)+6),>(SCN+(06*320)+7)
!BYTE >(SCN+(07*320)+0),>(SCN+(07*320)+1),>(SCN+(07*320)+2),>(SCN+(07*320)+3),>(SCN+(07*320)+4),>(SCN+(07*320)+5),>(SCN+(07*320)+6),>(SCN+(07*320)+7)
!BYTE >(SCN+(08*320)+0),>(SCN+(08*320)+1),>(SCN+(08*320)+2),>(SCN+(08*320)+3),>(SCN+(08*320)+4),>(SCN+(08*320)+5),>(SCN+(08*320)+6),>(SCN+(08*320)+7)
!BYTE >(SCN+(09*320)+0),>(SCN+(09*320)+1),>(SCN+(09*320)+2),>(SCN+(09*320)+3),>(SCN+(09*320)+4),>(SCN+(09*320)+5),>(SCN+(09*320)+6),>(SCN+(09*320)+7)
!BYTE >(SCN+(10*320)+0),>(SCN+(10*320)+1),>(SCN+(10*320)+2),>(SCN+(10*320)+3),>(SCN+(10*320)+4),>(SCN+(10*320)+5),>(SCN+(10*320)+6),>(SCN+(10*320)+7)
!BYTE >(SCN+(11*320)+0),>(SCN+(11*320)+1),>(SCN+(11*320)+2),>(SCN+(11*320)+3),>(SCN+(11*320)+4),>(SCN+(11*320)+5),>(SCN+(11*320)+6),>(SCN+(11*320)+7)
!BYTE >(SCN+(12*320)+0),>(SCN+(12*320)+1),>(SCN+(12*320)+2),>(SCN+(12*320)+3),>(SCN+(12*320)+4),>(SCN+(12*320)+5),>(SCN+(12*320)+6),>(SCN+(12*320)+7)
!BYTE >(SCN+(13*320)+0),>(SCN+(13*320)+1),>(SCN+(13*320)+2),>(SCN+(13*320)+3),>(SCN+(13*320)+4),>(SCN+(13*320)+5),>(SCN+(13*320)+6),>(SCN+(13*320)+7)
!BYTE >(SCN+(14*320)+0),>(SCN+(14*320)+1),>(SCN+(14*320)+2),>(SCN+(14*320)+3),>(SCN+(14*320)+4),>(SCN+(14*320)+5),>(SCN+(14*320)+6),>(SCN+(14*320)+7)
!BYTE >(SCN+(15*320)+0),>(SCN+(15*320)+1),>(SCN+(15*320)+2),>(SCN+(15*320)+3),>(SCN+(15*320)+4),>(SCN+(15*320)+5),>(SCN+(15*320)+6),>(SCN+(15*320)+7)
!BYTE >(SCN+(16*320)+0),>(SCN+(16*320)+1),>(SCN+(16*320)+2),>(SCN+(16*320)+3),>(SCN+(16*320)+4),>(SCN+(16*320)+5),>(SCN+(16*320)+6),>(SCN+(16*320)+7)
!BYTE >(SCN+(17*320)+0),>(SCN+(17*320)+1),>(SCN+(17*320)+2),>(SCN+(17*320)+3),>(SCN+(17*320)+4),>(SCN+(17*320)+5),>(SCN+(17*320)+6),>(SCN+(17*320)+7)
!BYTE >(SCN+(18*320)+0),>(SCN+(18*320)+1),>(SCN+(18*320)+2),>(SCN+(18*320)+3),>(SCN+(18*320)+4),>(SCN+(18*320)+5),>(SCN+(18*320)+6),>(SCN+(18*320)+7)
!BYTE >(SCN+(19*320)+0),>(SCN+(19*320)+1),>(SCN+(19*320)+2),>(SCN+(19*320)+3),>(SCN+(19*320)+4),>(SCN+(19*320)+5),>(SCN+(19*320)+6),>(SCN+(19*320)+7)
!BYTE >(SCN+(20*320)+0),>(SCN+(20*320)+1),>(SCN+(20*320)+2),>(SCN+(20*320)+3),>(SCN+(20*320)+4),>(SCN+(20*320)+5),>(SCN+(20*320)+6),>(SCN+(20*320)+7)
!BYTE >(SCN+(21*320)+0),>(SCN+(21*320)+1),>(SCN+(21*320)+2),>(SCN+(21*320)+3),>(SCN+(21*320)+4),>(SCN+(21*320)+5),>(SCN+(21*320)+6),>(SCN+(21*320)+7)
!BYTE >(SCN+(22*320)+0),>(SCN+(22*320)+1),>(SCN+(22*320)+2),>(SCN+(22*320)+3),>(SCN+(22*320)+4),>(SCN+(22*320)+5),>(SCN+(22*320)+6),>(SCN+(22*320)+7)
!BYTE >(SCN+(23*320)+0),>(SCN+(23*320)+1),>(SCN+(23*320)+2),>(SCN+(23*320)+3),>(SCN+(23*320)+4),>(SCN+(23*320)+5),>(SCN+(23*320)+6),>(SCN+(23*320)+7)
!BYTE >(SCN+(24*320)+0),>(SCN+(24*320)+1),>(SCN+(24*320)+2),>(SCN+(24*320)+3),>(SCN+(24*320)+4),>(SCN+(24*320)+5),>(SCN+(24*320)+6),>(SCN+(24*320)+7)

!align 255,0
SPR_SCN_TAB !WORD SPR_SCN.SPR_SCN_00, SPR_SCN.SPR_SCN_01, SPR_SCN.SPR_SCN_02, SPR_SCN.SPR_SCN_03, SPR_SCN.SPR_SCN_04, SPR_SCN.SPR_SCN_05, SPR_SCN.SPR_SCN_06, SPR_SCN.SPR_SCN_07  
SC_LO:
!BYTE <(SCN+(00*320)+0),<(SCN+(00*320)+1),<(SCN+(00*320)+2),<(SCN+(00*320)+3),<(SCN+(00*320)+4),<(SCN+(00*320)+5),<(SCN+(00*320)+6),<(SCN+(00*320)+7)
!BYTE <(SCN+(01*320)+0),<(SCN+(01*320)+1),<(SCN+(01*320)+2),<(SCN+(01*320)+3),<(SCN+(01*320)+4),<(SCN+(01*320)+5),<(SCN+(01*320)+6),<(SCN+(01*320)+7)
!BYTE <(SCN+(02*320)+0),<(SCN+(02*320)+1),<(SCN+(02*320)+2),<(SCN+(02*320)+3),<(SCN+(02*320)+4),<(SCN+(02*320)+5),<(SCN+(02*320)+6),<(SCN+(02*320)+7)
!BYTE <(SCN+(03*320)+0),<(SCN+(03*320)+1),<(SCN+(03*320)+2),<(SCN+(03*320)+3),<(SCN+(03*320)+4),<(SCN+(03*320)+5),<(SCN+(03*320)+6),<(SCN+(03*320)+7)
!BYTE <(SCN+(04*320)+0),<(SCN+(04*320)+1),<(SCN+(04*320)+2),<(SCN+(04*320)+3),<(SCN+(04*320)+4),<(SCN+(04*320)+5),<(SCN+(04*320)+6),<(SCN+(04*320)+7)
!BYTE <(SCN+(05*320)+0),<(SCN+(05*320)+1),<(SCN+(05*320)+2),<(SCN+(05*320)+3),<(SCN+(05*320)+4),<(SCN+(05*320)+5),<(SCN+(05*320)+6),<(SCN+(05*320)+7)
!BYTE <(SCN+(06*320)+0),<(SCN+(06*320)+1),<(SCN+(06*320)+2),<(SCN+(06*320)+3),<(SCN+(06*320)+4),<(SCN+(06*320)+5),<(SCN+(06*320)+6),<(SCN+(06*320)+7)
!BYTE <(SCN+(07*320)+0),<(SCN+(07*320)+1),<(SCN+(07*320)+2),<(SCN+(07*320)+3),<(SCN+(07*320)+4),<(SCN+(07*320)+5),<(SCN+(07*320)+6),<(SCN+(07*320)+7)
!BYTE <(SCN+(08*320)+0),<(SCN+(08*320)+1),<(SCN+(08*320)+2),<(SCN+(08*320)+3),<(SCN+(08*320)+4),<(SCN+(08*320)+5),<(SCN+(08*320)+6),<(SCN+(08*320)+7)
!BYTE <(SCN+(09*320)+0),<(SCN+(09*320)+1),<(SCN+(09*320)+2),<(SCN+(09*320)+3),<(SCN+(09*320)+4),<(SCN+(09*320)+5),<(SCN+(09*320)+6),<(SCN+(09*320)+7)
!BYTE <(SCN+(10*320)+0),<(SCN+(10*320)+1),<(SCN+(10*320)+2),<(SCN+(10*320)+3),<(SCN+(10*320)+4),<(SCN+(10*320)+5),<(SCN+(10*320)+6),<(SCN+(10*320)+7)
!BYTE <(SCN+(11*320)+0),<(SCN+(11*320)+1),<(SCN+(11*320)+2),<(SCN+(11*320)+3),<(SCN+(11*320)+4),<(SCN+(11*320)+5),<(SCN+(11*320)+6),<(SCN+(11*320)+7)
!BYTE <(SCN+(12*320)+0),<(SCN+(12*320)+1),<(SCN+(12*320)+2),<(SCN+(12*320)+3),<(SCN+(12*320)+4),<(SCN+(12*320)+5),<(SCN+(12*320)+6),<(SCN+(12*320)+7)
!BYTE <(SCN+(13*320)+0),<(SCN+(13*320)+1),<(SCN+(13*320)+2),<(SCN+(13*320)+3),<(SCN+(13*320)+4),<(SCN+(13*320)+5),<(SCN+(13*320)+6),<(SCN+(13*320)+7)
!BYTE <(SCN+(14*320)+0),<(SCN+(14*320)+1),<(SCN+(14*320)+2),<(SCN+(14*320)+3),<(SCN+(14*320)+4),<(SCN+(14*320)+5),<(SCN+(14*320)+6),<(SCN+(14*320)+7)
!BYTE <(SCN+(15*320)+0),<(SCN+(15*320)+1),<(SCN+(15*320)+2),<(SCN+(15*320)+3),<(SCN+(15*320)+4),<(SCN+(15*320)+5),<(SCN+(15*320)+6),<(SCN+(15*320)+7)
!BYTE <(SCN+(16*320)+0),<(SCN+(16*320)+1),<(SCN+(16*320)+2),<(SCN+(16*320)+3),<(SCN+(16*320)+4),<(SCN+(16*320)+5),<(SCN+(16*320)+6),<(SCN+(16*320)+7)
!BYTE <(SCN+(17*320)+0),<(SCN+(17*320)+1),<(SCN+(17*320)+2),<(SCN+(17*320)+3),<(SCN+(17*320)+4),<(SCN+(17*320)+5),<(SCN+(17*320)+6),<(SCN+(17*320)+7)
!BYTE <(SCN+(18*320)+0),<(SCN+(18*320)+1),<(SCN+(18*320)+2),<(SCN+(18*320)+3),<(SCN+(18*320)+4),<(SCN+(18*320)+5),<(SCN+(18*320)+6),<(SCN+(18*320)+7)
!BYTE <(SCN+(19*320)+0),<(SCN+(19*320)+1),<(SCN+(19*320)+2),<(SCN+(19*320)+3),<(SCN+(19*320)+4),<(SCN+(19*320)+5),<(SCN+(19*320)+6),<(SCN+(19*320)+7)
!BYTE <(SCN+(20*320)+0),<(SCN+(20*320)+1),<(SCN+(20*320)+2),<(SCN+(20*320)+3),<(SCN+(20*320)+4),<(SCN+(20*320)+5),<(SCN+(20*320)+6),<(SCN+(20*320)+7)
!BYTE <(SCN+(21*320)+0),<(SCN+(21*320)+1),<(SCN+(21*320)+2),<(SCN+(21*320)+3),<(SCN+(21*320)+4),<(SCN+(21*320)+5),<(SCN+(21*320)+6),<(SCN+(21*320)+7)
!BYTE <(SCN+(22*320)+0),<(SCN+(22*320)+1),<(SCN+(22*320)+2),<(SCN+(22*320)+3),<(SCN+(22*320)+4),<(SCN+(22*320)+5),<(SCN+(22*320)+6),<(SCN+(22*320)+7)
!BYTE <(SCN+(23*320)+0),<(SCN+(23*320)+1),<(SCN+(23*320)+2),<(SCN+(23*320)+3),<(SCN+(23*320)+4),<(SCN+(23*320)+5),<(SCN+(23*320)+6),<(SCN+(23*320)+7)
!BYTE <(SCN+(24*320)+0),<(SCN+(24*320)+1),<(SCN+(24*320)+2),<(SCN+(24*320)+3),<(SCN+(24*320)+4),<(SCN+(24*320)+5),<(SCN+(24*320)+6),<(SCN+(24*320)+7)

!ALIGN 255,0

SPR00_AND_LO !BYTE <(SPR00_AND_0),<(SPR00_AND_1),<(SPR00_AND_2),<(SPR00_AND_3)
SPR00_AND_HI !BYTE >(SPR00_AND_0),>(SPR00_AND_1),>(SPR00_AND_2),>(SPR00_AND_3)
SPR00_ORA_LO !BYTE <(SPR00_ORA_0),<(SPR00_ORA_1),<(SPR00_ORA_2),<(SPR00_ORA_3)

SPRITE_AND_LO_LO !BYTE <SPR00_AND_LO
SPRITE_AND_LO_HI !BYTE >SPR00_AND_LO
SPRITE_AND_HI_LO !BYTE <SPR00_AND_HI
SPRITE_AND_HI_HI !BYTE >SPR00_AND_HI
SPRITE_ORA_LO_LO !BYTE <SPR00_ORA_LO
SPRITE_ORA_LO_HI !BYTE >SPR00_ORA_LO

!ALIGN 255,0
SPR00_AND_0
!for I = 0 TO 23
!BYTE %11111111
!end
!for I = 0 TO 23
!BYTE %00000000
!end
!for I = 0 TO 23
!BYTE %00000000
!end

;!BYTE %11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111
;!BYTE %00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000
;!BYTE %00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000

;!ALIGN 127,0
SPR00_ORA_0
!for I = 0 TO 23
!BYTE %00000000
!end
!for I = 0 TO 23
!BYTE %11111111
!end
!for I = 0 TO 23
!BYTE %11111111
!end

;!BYTE %00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000
;!BYTE %11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111
;!BYTE %11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111

!ALIGN 255,0
SPR00_AND_1
!for I = 0 TO 23
!BYTE %00111111
!end
!for I = 0 TO 23
!BYTE %00000000
!end
!for I = 0 TO 23
!BYTE %11000000
!end
;!BYTE %00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111
;!BYTE %00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000
;!BYTE %11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000

!ALIGN 127,0
SPR00_ORA_1
!for I = 0 TO 23
!BYTE %11000000
!end
!for I = 0 TO 23
!BYTE %11111111
!end
!for I = 0 TO 23
!BYTE %00111111
!end
;!BYTE %11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000,%11000000
;!BYTE %11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111
;!BYTE %00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111,%00111111

!ALIGN 255,0
SPR00_AND_2
!for I = 0 TO 23
!BYTE %00001111
!end
!for I = 0 TO 23
!BYTE %00000000
!end
!for I = 0 TO 23
!BYTE %11110000
!end
;!BYTE %00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111
;!BYTE %00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000
;!BYTE %11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000

;!ALIGN 127,0
SPR00_ORA_2
!for I = 0 TO 23
!BYTE %11110000
!end
!for I = 0 TO 23
!BYTE %11111111
!end
!for I = 0 TO 23
!BYTE %00001111
!end
;!BYTE %11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000,%11110000
;!BYTE %11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111
;!BYTE %00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111,%00001111

!ALIGN 255,0
SPR00_AND_3
!for I = 0 TO 23
!BYTE %00000011
!end
!for I = 0 TO 23
!BYTE %00000000
!end
!for I = 0 TO 23
!BYTE %11111100
!end
;!BYTE %00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011
;!BYTE %00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000,%00000000
;!BYTE %11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100

;!ALIGN 127,0
SPR00_ORA_3
!for I = 0 TO 23
!BYTE %11111100
!end
!for I = 0 TO 23
!BYTE %11111111
!end
!for I = 0 TO 23
!BYTE %00000011
!end
;!BYTE %11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100,%11111100
;!BYTE %11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111,%11111111
;!BYTE %00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011,%00000011

SCN = 24*1024 ; 40*1024 ; 24*1024
SCN_BUF = 56*1024 ; 41984 ; 41 *1024
COL_BUF = SCN - 1024 ; SCN-$2000
